# Generated by Django 4.2.6 on 2023-10-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=200)),
                ('detalle_corto', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('S', 'Suspensión de actividades'), ('C', 'Suspensíon de clase'), ('I', 'Información')], max_length=1)),
                ('visible', models.BooleanField()),
                ('fecha_de_publicacion', models.DateTimeField()),
                ('fecha_ultima_publicacion', models.DateTimeField()),
                ('publicado_por', models.CharField(max_length=50)),
                ('modificado_por', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entidad')),
            ],
        ),
    ]
